name: duality
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask_cors
  - pymongo
  - autopep8
  - python-dotenv
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-auth-oauthlib